name: boleto_organizer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  firebase_core: ^1.3.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  animated_card: ^2.0.0
  injectable: ^1.4.1
  get_it: ^7.1.3
  camera: ^0.8.1+3
  google_ml_kit: ^0.6.0
  image_picker: ^0.8.1+3
  flutter_masked_text2: ^0.9.1
  font_awesome_flutter: ^9.1.0
  fluttertoast: ^8.0.7

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
